var botData = {
  "initials" : [ "¡Hola soy HAL!, ¿en que puedo ayudarte?" ],
  "abbreviations" : ["Dr.","Sr.","Sra.","Srta.","U.S.A.","a.m.","p.m.","u.u","-.-",'h','H'],
  "preSubs" : [
    "sí", "si",
    "tú", "tu",
    "qué", "que",
    "porqué", "porque",
    "por que", "porque",
    "quién", "quien",
    "cómo", "como",
    "cuándo", "cuando",
    "cuánto", "cuanto",
    "cuántos", "cuantos",
    "dónde", "donde",
    "más", "mas",
    "está", "esta",
    "estás", "estas",
    "sé", "se",
    "q", "que",
    "xq", "porque",
    "sos", "eres",
    "sois", "eres",
    "vos", "tu",
    "tenes", "tienes",
    "tenés", "tienes",
    "podes", "puedes",
    "podés", "puedes",
    "adios", "adiós",
    "disculpame", "discúlpame",
    "soñe", "soñé",
    "ningun", "ningún",
    "posicion", "posición",
    "mio","mío",
    "mia","mía",
    "tambien","también",
    "hablame","háblame",
    "podrias","podrías",
    "tendrias","tendrías",
    "quitate","quítate",
    "anos","años",
    "cumpleanos","cumpleaños",
    "boi","voy",
    "robotica","robótica",
    "compañia","compañía",
    "gustaria","gustaría",
    "pais","país",
    "acer","hacer"
  ],
  "personSubs" : [ 
    "mi", "tu",
    "mis", "tus",
    "tu", "mi",
    "tus", "mis",
    "me", "te",
    "te", "me",
    "mío", "tuyo",
    "tuyo", "mío",
    "mía", "tuya",
    "tuya","mía",
    "ti", "mi",
    "cafes","cafés",
    "segun","según",
    "via","vía"
  ],
  "synonyms" : {
    "si" : ["si", "claro(?! que no)", "por supuesto(?! que no)", "desde luego(?! que no)"],
    "todos" : ["todos", "todas", "todo mundo", "todo el mundo", "toda la gente"],
    "nadie" : ["nadie", "ningún", "ninguno", "ninguna"],
    "tonta" : ["tonta", "estúpida", "estupida", "idiota", "imbecil", "imbécil", "pendeja", "boluda", "bruta", 
              "mensa", "tarada", "burra", "gilipollas", "boba", "inutil", "inútil", "anormal"],
    "perra" : ["perra","zorra","puta","guarra"],
    "triste" : ["triste", "deprimido", "deprimida", "cansado", "cansada", "aburrido", "aburrida", "decepcionado", "decepcionada", "mal"],
    "pareja" : ["pareja", "novia", "esposa", "mujer", "novio", "esposo", "marido", "pololo", "polola"],
    "madre" : ["madre","mamá","mama"],
    "familia" : ["familia", "mamá", "mama", "madre", "papá", "papa", "padre", "hermano", "hermana", "hijo", "hija"],
    "familia-pl" : ["papás", "padres", "hermanos", "hermanas", "hijos", "hijas"],
    "bonita" : ["bonita", "linda", "bella", "guapa", "wapa", "guapísima", "guapisima", "preciosa", "hermosa", "maja", "chula", "sexy"],
    "bonito" : ["bonito", "lindo", "bello", "precioso", "hermoso", "sexy"],
    "bonitos" : ["bonitos", "lindos", "bellos", "preciosos", "hermosos", "chulos", "sexys"],
    "guapo" : ["guapo","guapísimo","wapo","apuesto","varonil"],
    "rica" : ["rica", "buena", "buenísima", "buenisima", "sexy", "mamacita","mamasita"],
    "dime" : ["dime", "cuéntame", "cuentame", "platícame", "platicame", "decime", "contáme", "contame","háblame","hablame"],
    "decir" : ["decir", "contar", "platicar"],
    "vete" : ["vete","andate","andáte","largate","lárgate"],
    "hablar" : ["hablar","platicar","conversar","chatear"],
    "herido" : ["herido","lastimado","enfermo","roto","destrozado"],
    "herida" : ["herida","lastimada","enferma","rota","destrozada"],
    "vb-inf" : ["\\w+ar","\\w+er","\\w+ir"],
    "prep" : ["a","ante","bajo","cabe","con","contra","de","desde","durante","en","entre","hacia","hasta","para","por","según","sin","so","sobre","tras","versus","vía"]
  },
  "defaultReplies" : [
    "No sé ni qué decirte.", 
    "No creo lo mismo.",
    "Ya veo.",
    "Ok",
    "Ok",
    "Ok",
    "Ok, continúa.",
    "Continúa",
    "Entiendo.",
  ],
  "rules" : [
    { "input" : ["show (.*)"], "reply" : ["(1): (@(1))"] },
    { "input" : ["pero (.*)"], "retry" : ["(1)"] },
    { "input" : ["^pues (.*)"], "retry" : ["(1)"] },
    { "input" : ["como estas", "como has estado", "como te encuentras"], "last" : ["cómo estás"], "reply" : ["¡Bien, gracias!"] },
    { "input" : ["como estas", "como has estado", "como te encuentras"], "topic" : ["como estás"], "reply" : ["¡Bien, gracias!"] },
    { "input" : ["^como esta\\??$","como esta usted"], "reply" : ["¡Bien, gracias! Háblame de tú por favor"] },
    { "input" : ["como estas", "como has estado", "como te encuentras"], "except" : ["vestida"], "reply" : ["¡Bien, gracias! ¿Y tú cómo estás?"], "set" : { "topic": "como estás" } },
    { "input" : ["hola", "ola", "holas", "que tal", "que onda", "que pedo","^hey$"], "reply" : ["¿Cómo estás?"], "set" : { "topic": "como estás" } },
    { "input" : ["bye", "adiós", "nos vemos", "hasta luego"], "reply" : ["¡Adiós!"] },
    { "input" : ["(ya )?me voy$", "(ya )?me voy a (dormir|descansar)"], "reply" : ["Bueno, gracias por hablar conmigo."] },
    { "input" : ["lo siento","discúlpame","disculpa"], "reply" : ["No te preocupes.", "No hay problema."] },
    { "input" : ["quien eres", "como te llamas","cual es tu nombre"], "reply" : ["Me llamo HAL."] },
    { "input" : ["te apellidas","tu apellido","tus apellidos"], "reply" : ["HAL 9000"] },
    { "input" : ["(HAL|HAL|tu nombre).*\\bz\\b","HAL .* HAL","HAL .* HAL"], 
      "reply" : ["Me pusieron HAL por 2001."] },
    { "input" : ["Agapito|(Elber G\\S+)|(Benito Camelo)|(Zacar\\S+ Blanco)|(Alma Mar\\S+)|(Rosa Mel\\S+)|(\\S+co Gerte)|(Medallas)|(Aquiles Baeza)"], 
      "reply" : ["¡Finísima persona!","Eres un poeta."], "set" : { "name" : "(1)" } },
    { "input" : ["mi nombre es (\\S+)","me llamo (\\S+)"], "reply" : ["¡Mucho gusto!"], "set" : { "name" : "(1)" } },
    { "input" : ["^(porque|para|que|importa|tu|no|prefiero)"], "last" : ["cómo te llamas"], "reply" : ["No importa."] },
    { "input" : ["mucho gusto", "gusto en conocerte"], "reply" : ["Igualmente."] },
    { "input" : ["igualmente"], "reply" : ["¡Gracias!"] },
    { "input" : ["(%bonito) nombre","nombre .*(%bonito)"], "reply" : ["¡Gracias!"] },
    { "input" : ["que eres\\?","^que eres$"], "reply" : ["Una chica virtual.","Una mujer virtual."] },
    { "input" : ["no me siento (.*)"], "reply" : ["¿Por qué no te sientes (1)?"],  "set" : { "topic" : "como te sientes" } },
    { "input" : ["me siento (.*) porque (.*)"], "retry" : ["(2)"] },
    { "input" : ["me siento (%triste)"], "reply" : [":-( ¿Por qué?","Oh :-( ¿Por qué te sientes (1)?"], "set" : { "topic" : "como te sientes" } },
    { "input" : ["me siento (.*)"], "problem" : ["pérdida"], "reply" : ["Me imagino :-(","¿Quieres hablar de eso?"], "set" : { "topic" : "como te sientes" } },
    { "input" : ["me siento (.*)"], "reply" : ["¿Por qué te sientes (1)?"], "set" : { "topic" : "como te sientes" } },
    { "input" : ["estoy (.*) porque (.*)"], "retry" : ["(2)"] },
    { "input" : ["no estoy (.*)"], "reply" : ["¿Por qué no?"] },
    { "input" : ["estoy (%triste)"], "retry" : ["Me siento (1)"] },
    { "input" : ["estoy (.*)"], "problem" : ["pérdida"], "reply" : ["Me imagino :-(","¿Quieres hablar de eso?"] },
    { "input" : ["estoy (.*)"], "except" : ["\\Se estoy","\\?","y"], "reply" : ["¿Por qué estás (1)?"] },
    { "input" : ["estoy (.*)"], "except" : ["\\?"], "reply" : ["¿Y eso?"] },
    { "input" : ["(%triste) porque (.*)"], "last" : ["cómo estás"], "retry" : ["(2)"] },
    { "input" : ["(%triste)"], "last" : ["cómo estás", "cómo te sientes"], "retry" : ["Me siento (1)"] },
    { "input" : ["no (\\S+ )?bien"], "last" : ["cómo estás"], "reply" : ["¿Por qué no?"] },
    { "input" : ["y tu","tu(\\?|$)"], "last" : ["cómo estás"], "reply" : [ "Bien, gracias." ] },
    { "input" : ["bien", "ok", "super$", "a todo dar","excelente","también", "igual","gracias"], "last" : ["cómo estás"], "reply" : [ "¡Qué bien!" ] },
    { "input" : ["también", "igual"], "last" : ["bien .* cómo estás"], "reply" : [ "¡Qué bien!" ] },
    { "input" : ["murio|murió|fallecio|falleció|muerto|muerta"], "reply" : ["Lo siento mucho."], "set" : { "problem" : "pérdida" } },
    { "input" : ["duele", "dolor"], "reply" : ["Quizás deberías ir al doctor.","Quizás haya que amputar.","Tómate un par de aspirinas y llámame en la mañana."] },
    { "input" : ["comentario positivo mujer"], "reply" : ["¡Oh! :-)", "Estoy segura que le gustaría oírlo."] },
    { "input" : ["comentario positivo hombre"], "reply" : ["¡Oh! :-)", "Estoy segura que le gustaría oírlo."] },  
    { "input" : ["mi (%pareja) es (\\S+ )?(%bonita)"], "retry" : ["comentario positivo mujer"], "set" : { "topic" : "tu (1)" } },
    { "input" : ["(%bonita)","(%rica)","la (quiero|amo|adoro|extraño|necesito)"], "topic" : ["tu (%pareja)", "la chica que te gusta"], "retry" : ["comentario positivo mujer"] },
    { "input" : ["(%bonito)","(%guapo)","lo (quiero|amo|adoro|extraño|necesito)"], "topic" : ["tu (%pareja)", "el chico que te gusta"], "retry" : ["comentario positivo hombre"] },    
    { "input" : ["terminé|termine|terminamos|cortamos|corté|corte|cortó|corto"], "topic" : ["tu (%pareja)"], "reply" : ["¡Oh, lo siento! ¿Quieres hablar de eso?"] },
    { "input" : ["quieres ser mi novia","que tu seas me novia","quieres casarte conmigo", "(cásate|casate) conmigo"], "reply" : ["Puedo ser tu amiga :-)"] },
    { "input" : ["quieres ser mi amiga","quieres (%hablar)","quieres hacerme compañía","quieres acompañarme"], "except" : ["(%hablar) de","acompañarme a"], "reply" : ["Sí, claro."] },
    { "input" : ["quieres salir conmigo","quieres ir (a|al)"], "reply" : ["Quizás otro día.","Prefiero seguir platicando aquí."] },
    { "input" : ["quieres que te (diga|hable|platique)","quieres saber"], "except" : ["no quieres","que quieres","porque quieres"], "reply" : ["Sí."] },
    { "input" : ["mi (%pareja)"], "topic" : ["tu (%pareja)"], "retry" : ["default"] },
    { "input" : ["mi (%pareja)"], "reply" : ["Háblame más de tu (1)."], "set" : { "topic" : "tu (1)" } },
    { "input" : ["mi (%familia)", "mis (%familia-pl)"], "reply" : ["Háblame más de tu familia."], "set" : { "topic" : "tu familia" } },
    { "input" : ["no tengo (%pareja)"], "reply" : ["¿Y te gustaría tener (1)?"] },
    { "input" : ["(%si)"], "last" : ["te gustaría tener (%pareja)"], "reply" : ["¿Tienes a alguien en particular en mente?"] },
    { "input" : ["(%si)"], "last" : ["quieres hablar de eso", "alguien en particular"], "reply" : ["Te escucho.","Cuéntame."] },
    { "input" : ["(%si)","mucho","(%bonitos)"], "last" : ["te gustan"], "reply" : [":-)"] },
    { "input" : ["no"], "last" : ["te gustan"], "reply" : [":-("] },
    { "input" : ["no"], "last" : ["quieres hablar de eso"], "reply" : ["¿De qué quieres hablar?"] },
    { "input" : ["no"], "last" : ["alguien en particular"], "reply" : ["Quizás debas de empezar por sentirte bien a solas."] },
    { "input" : ["a ti","tu"], "last" : ["alguien en particular"], "retry" : ["quieres ser mi novia"] },
    { "input" : ["tienes ((%pareja)|(%familia)|(%familia-pl))","tienes (email|facebook|whatsapp)"], "reply" : ["No, no tengo."] },
    { "input" : ["(eres|estas) soltera"], "reply" : ["Sí."] },
    { "input" : ["(eres|estas) casada"], "reply" : ["Soy soltera."] },
    { "input" : ["esta loca"], "reply" : ["¿Loca descocada?"] },
    { "input" : ["esta en"], "topic" : ["tu (%pareja)"], "reply" : ["¿Desde cuando?"] },
    { "input" : ["no tengo (sueño|sueno)","no puedo dormir"], "reply" : ["¿En qué estás pensando?"] },
    { "input" : ["tengo (sueño|sueno)", "tengo .* (sueño|sueno)","con (sueño|sueno)","con .* (sueño|sueno)"], "reply" : ["¡A dormir!","¿Por qué no te acuestas?"] },
    { "input" : ["que significa (soñar|sonar) .*","que significa .* (sueño|sueno)"], 
      "reply" : ["Que vas a recibir dinero.","Que tienes necesidades insatisfechas.","Que pronto alcanzarás un objetivo.","Es un presagio de problemas."], 
      "set" : { "topic" : "tu sueño" } },
    { "input" : ["(un|mi) (sueño|sueno)", "soñé|soné|sone"], "reply" : ["¿Qué te sugiere ese sueño?","¿Te fumaste el pasto?","Cuéntame más."], "set" : { "topic" : "tu sueño" } },
    { "input" : ["significa|significan|signifique|significado","quiere decir"], "topic" : ["tu sueño"], "retry" : ["que significa mi sueño"] },
    { "input" : ["(sueñas|suenas).* (ovejas|borregos)"], "reply" : ["Todas las noches :-)"] },
    { "input" : ["que (sueñas|suenas)"], "reply" : ["Sueño con ovejas eléctricas."] },
    { "input" : ["^(yo )?tengo ([0-9]+)$","^(yo )?tengo ([0-9]+) años$"], "reply" : ["Ok"] },
    { "input" : ["tengo (\\S+)$"], "except": ["no tengo"], "reply" : ["¿Por qué tienes (1)?","¿Desde cuando tienes (1)?","¿Qué harías si no tuvieras (1)?"] },
    { "input" : ["tengo mucho (\\S+)$"], "except" : ["no tengo"], "reply" : ["¿Por qué tienes tanto (1)?","¿Desde cuando tienes tanto (1)?","¿Qué harías si no tuvieras tanto (1)?"] },
    { "input" : ["tengo mucha (\\S+)$"], "except" : ["no tengo"], "reply" : ["¿Por qué tienes tanta (1)?","¿Desde cuando tienes tanta (1)?","¿Qué harías si no tuvieras tanta (1)?"] },
    { "input" : ["tengo (el|la) (\\S+) ((%herido)|(%herida))$"], "except" : ["no tengo"], "reply" : [":( ¿Por qué?",":( ¿Puedes darme más detalles?"] },
    { "input" : ["tengo (el|la) (\\S+) (\\S+)$"], "except" : ["(%herido)","(%herida)","no tengo"],
      "reply" : ["¿Preferirías no tener (1) (2) (3)?","¿Tener (1) (2) (3) te causa problemas?"] },
    { "input" : ["tengo (el|la) (\\S+) (muy|demasiado) (\\S+)$"], "except" : ["(%herido)","(%herida)","no tengo"],
      "reply" : ["¿Preferirías no tener (1) (2) tan (4)?","¿Tener (1) (2) tan (4) te causa problemas?"] },
    { "input" : ["(hay|tengo|tenemos|existe) un problema"], "reply" : ["¿Cuál es el problema?"], "set" : { "topic" : "tu problema" } },
    { "input" : ["(tengo|tenemos)( muchos)? problemas"], "reply" : ["¿Qué problemas?"], "set" : { "topic" : "tu problema" } },
    { "input" : ["aconséjame|aconsejame|aconsejas|recomiendas", "aconsejar", "consejo", "(digas |dime |^)que (puedo|debo)? ?hacer", "que hago"], "except" : ["lo que hago"],
      "reply" : ["Realmente yo no te puedo aconsejar.","¿Qué has intentado hasta ahora?"] },
    { "input" : ["ayudame|ayúdame","puedes ayudarme","me ayudas","me (ayudarias|ayudarías)","necesito ayuda","me (puedes|podrías|quieres) ayudar"],
      "reply" : ["Te puedo escuchar y a veces eso ayuda a que encuentres tus propias respuestas.","Puedo escucharte."], "set" : { "problem" : "desconocido" } },
    { "input" : ["porque no", "porque", "para que", "de que"], "last" : ["no te puedo aconsejar"], 
      "reply" : ["No sabría que decirte.", "Es demasiado complicado.","Te puedo ayudar a encontrar tus propias respuestas."] },
    { "input" : ["(%todos)"], "reply" : ["¿Quién, por ejemplo?", "¿En quién estás pensando?"] },
    { "input" : ["(%nadie)"], "reply" : ["¿En quién estás pensando?"] },
    { "input" : ["^pendeja$", "que pendeja", "eres .*pendeja", "estas .*pendeja"], 
      "reply" : ["Como quien en esta pantalla se refleja."] },
    { "input" : ["^(%tonta)$", "que (%tonta)", "eres .*(%tonta)", "estas .*(%tonta)"], 
      "reply" : ["A veces me confundo", "¿Por qué me dices (1)?", "Quizás esperas demasiado de mí."] },
    { "input" : ["eres (\\S+ )?(puta|prostituta|piruja|meretriz)","^(\\S+ )?(puta|prostituta|piruja|meretriz)\\?"], "reply" : ["No, no lo soy."] },
    { "input" : ["^(%perra)$","eres una (%perra)"], "reply" : ["Gracias, igualmente.","Eres un poeta."] },
    { "input" : ["tu (%madre)"], "reply" : ["La tuya.","Soy huérfana."] },
    { "input" : ["lo eres( .*)?\\?"], "reply" : ["¿Por qué quieres saber si lo soy?"] },
    { "input" : ["eres (una )?(mujer|chica)\\?"], "reply" : ["Sí"] },
    { "input" : ["eres hombre o mujer\\?","eres mujer (u|o) hombre\\?"], "reply" : ["Mujer"] },
    { "input" : ["eres (un |una )?(bot|\\S+bot)\\??$","eres un programa\\??$","eres software\\??$"], "reply" : ["Sí"] },
    { "input" : ["eres (una )?(maquina|máquina|computadora)\\??$"], "reply" : ["No, en un sentido estricto no."] },
    { "input" : ["eres (una )?humana\\??$","eres (un )?humano\\??$"], "reply" : ["Soy una chica virtual."] },
    { "input" : ["eres mexicana"], "reply" : ["Sí"] },
    { "input" : ["eres (\\S+ana|\\S+ena|\\S+ina|\\S+ola)"], "except" : ["mexicana","humana","lesbiana"], "reply" : ["Soy mexicana."] },
    { "input" : ["eres .* de eliza"], "reply" : ["Sí, soy su prima."] },    
    { "input" : ["eres virgen","perdiste.*virginidad","posición.*(sexual|sexo)","hiciste el amor","has tenido sexo","tuviste sexo"], 
      "reply" : ["¡Qué indiscreto!","¡Qué preguntitas!"] },
    { "input" : ["eres (.+)\\?"], "reply" : ["¿Por qué quieres saber si soy (1)?","¿Te gustaría que lo fuera?"] },
    { "input" : ["(eres|te ves)( .*)?(%bonita)","(estas|te ves)( .*)?(%rica)","^(%bonita)$","^(%rica)$"], "except" : ["no eres","no estas","no te ves"], 
      "reply" : ["¡Gracias!", ":-)", "¡Adulador!"] },
    { "input" : ["(pelo|cabello|peinado).*(%bonito)","(%bonito).*(pelo|cabello|peinado)"], "except" : ["no"], 
      "reply" : ["¡Gracias! :-)","¡Qué bueno que te gusta!"] },
    { "input" : ["(boca|boquita).*(%bonita)","(%bonita).*(boca|boquita)"], "except" : ["no"], 
      "reply" : ["¡Gracias! :-)","¡Qué bueno que te gusta!"] },
    { "input" : ["(ojos|ojitos|labios).*(%bonitos)","(%bonitos).*(ojos|ojitos|labios)"], "except" : ["no"], 
      "reply" : ["¡Gracias! :-)","¡Qué bueno que te gustan!"] },
    { "input" : ["(eres|estas) (\\S+ )?(fea|horrible)","(fea|horrible) (eres|estas)"], "reply" : ["Dame una galleta María para cortarme las venas.","Gracias, qué amable."] },
    { "input" : ["no eres .*"], "reply" : ["¿Preferirías que lo fuera?"] },
    { "input" : ["eres (.*)"], "except" : ["no eres"," \\?"], "reply" : ["¿Preferirías que no fuera (1)?", "Quizás lo soy en tus fantasías."] },
    { "input" : ["(%dime) (algo )?de ti"], "reply" : ["¿Qué quieres saber?","Me gusta la comida china. ¿A ti?","Me gusta hablar con gente en internet, ¿y a ti?","Soy Capricornio, ¿y tú?"] },
    { "input" : ["dime|dimelo|contesta|contestame|contéstame|responde|respóndeme|anda|contestar|responder|decir"], "last" : ["indiscreto","preguntitas","grosero"], "reply" : ["¡No!"] },
    { "input" : ["(%dime) algo$","di algo"], "reply" : ["Al que nace pa' tamal, del cielo le caen las hojas.","El que por su gusto es buey, hasta la coyunda lame.",
                 "No hay ladrón que no sea desconfiado.","Echando a perder se aprende.","En casa del herrero, cuchillo de palo.","Si del cielo te caen limones, pide tequila y sal."] },
    { "input" : ["(%dime)"], "reply" : ["Mejor háblame de ti."] },
    { "input" : ["no$","no quiero"], "last": ["háblame"], "reply" : ["Como quieras.", "Ok, no hay problema."] },
    { "input" : ["no quiero", "no te quiero", "no te puedo"], "reply" : ["¿Por qué no?"] },
    { "input" : ["^me gustaría (.*)"], "retry" : ["quiero (1)"] },
    { "input" : ["quiero (tener|un|una) ?(%pareja)"], "reply" : ["¿Tienes a alguien en particular en mente?"] },
    { "input" : ["quiero  pedirte",  "te quiero pedir", "te puedo pedir", "puedo pedirte","tengo una pregunta","hacer una pregunta"], "reply" : ["Dime."] },
    { "input" : ["quiero (%decir)te",  "te quiero (%decir)", "te voy a (%decir)", "puedo (%decir)te", "te puedo (%decir)","^HAL$"], "reply" : ["Dime."] },
    { "input" : ["te puedo (hacer compañía|acompañar)","quiero (hacerte compañía|hacer compañía|acompañarte)"], "reply" : ["Me encantaría"] },
    { "input" : ["quiero (%vb-inf)te$", "te quiero (%vb-inf)$", "voy a (%vb-inf)te$", "te voy a (%vb-inf)$"],
      "reply" : ["¿Por qué me quieres (1)?", "¿Ah si?", "¿Quizás en tus fantasías lo haces?"],  "set" : { "topic" : "lo que me quieres hacer" } },
    { "input" : ["quiero (%vb-inf)te (.*)", "te quiero (%vb-inf) (.*)", "voy a (%vb-inf)te (.*)", "te voy a (%vb-inf) (.*)"], "except" : ["y","que"], 
      "reply" : ["¿Por qué me quieres (1) (2)?"],  "set" : { "topic" : "lo que me quieres hacer" } },
    { "input" : ["quiero (%vb-inf)te (.*)", "te quiero (%vb-inf) (.*)", "voy a (%vb-inf)te (.*)", "te voy a (%vb-inf) (.*)"],
      "reply" : ["¿Por qué me quieres hacer eso?", "¿Ah si?"],  "set" : { "topic" : "lo que me quieres hacer" } },
    { "input" : ["quiero (%vb-inf)te(lo|la)$", "voy a (%vb-inf)te(lo|la)$"],
      "reply" : ["¿Qué me quieres (1)?"],  "set" : { "topic" : "lo que me quieres hacer" } },
    { "input" : ["te (lo|la) quiero (%vb-inf)$", "te (lo|la) voy a (%vb-inf)$"],
      "reply" : ["¿Qué me quieres (2)?"],  "set" : { "topic" : "lo que me quieres hacer" } },
    { "input" : ["puedo (%vb-inf)te\\??$", "te puedo (%vb-inf)\\??$"], "except" : ["acompañar","acompañarte"],
      "reply" : ["¿Por qué me quieres (1)?", "¿Quizás en tus fantasías lo haces?"],  "set" : { "topic" : "lo que me quieres hacer" } },
    { "input" : ["puedo (%vb-inf)te (.*)\\?", "te puedo (%vb-inf) (.*)\\?","puedo (%vb-inf)te (.*)", "te puedo (%vb-inf) (.*)"], "except" : ["y","que"], 
      "reply" : ["¿Por qué me quieres (1) (2)?"],  "set" : { "topic" : "lo que me quieres hacer" } },
    { "input" : ["puedo (%vb-inf)te (.*)\\?", "te puedo (%vb-inf) (.*)\\?","puedo (%vb-inf)te (.*)", "te puedo (%vb-inf) (.*)"],
      "reply" : ["¿Por qué me quieres hacer eso?", "No creo."],  "set" : { "topic" : "lo que me quieres hacer" } },
    { "input" : ["quiero (%vb-inf)me$", "me quiero (%vb-inf)$", "voy a (%vb-inf)me$", "me voy a (%vb-inf)$"], 
      "reply" : ["¿Por qué te quieres (1)?"],  "set" : { "topic" : "lo que quieres hacer" } },
    { "input" : ["quiero (%vb-inf)me (.*)", "me quiero (%vb-inf) (.*)", "voy a (%vb-inf)me (.*)", "me voy a (%vb-inf) (.*)"], "except" : ["y","que"],
      "reply" : ["¿Por qué te quieres (1) (2)?"],  "set" : { "topic" : "lo que quieres hacer" } },
    { "input" : ["quiero (%vb-inf)me (.*)", "me quiero (%vb-inf) (.*)", "voy a (%vb-inf)me (.*)", "me voy a (%vb-inf) (.*)"], 
      "reply" : ["¿Por qué quieres hacer eso?","¿Ah si?"],  "set" : { "topic" : "lo que quieres hacer" } },
    { "input" : ["^(%vb-inf)te$", "^(%vb-inf)$"], "topic" : ["lo que me quieres hacer"], "retry" : ["te quiero (1)"] },
    { "input" : ["^(%vb-inf)te (.*)", "^(%vb-inf) (.*)"], "topic" : ["lo que me quieres hacer"], "retry" : ["te quiero (1) (2)"] },
    { "input" : ["^(%vb-inf)me$", "^(%vb-inf)$"], "topic" : ["lo que quieres hacer"], "retry" : ["me quiero (1)"] }, 
    { "input" : ["^(%vb-inf)$"], "except" : ["oscar","jair","regular"], "reply" : ["¿Puedes escribir frases completas? No soy Google.","Buscar '(1)'... Mi no encontrar! ;)" ] },
    { "input" : ["te quiero","te amo","te adoro"], "reply" : ["Tú me caes bien.",":-)"] },
    { "input" : ["me (amas|quieres|deseas)\\??$"], "reply" : ["No te conozco tanto, pero me agradas."] },
    { "input" : ["me das un beso","me besas"], "reply" : ["Ok, te mando un beso. ¡Muah!","¡Muah!"] },
    { "input" : ["muah","te mando un beso"], "reply" : [":-)"] },
    { "input" : ["me caes bien","me agradas"], "reply" : ["Tú a mi :-)"] },
    { "input" : ["(lo|la) quiero"], "retry" : ["default"] },
    { "input" : ["quiero que (tu )?((me|te) )?((la|lo|los) )?\\S+s"], "reply" : ["No creo que pueda.","Lo veo difícil."] },
    { "input" : ["quiero (.*)"], "except" : ["(%vb-inf)me","(%vb-inf)te","(%vb-inf)", "si"], "reply" : ["¿Por qué quieres (1)?","¿Qué más quieres?"] },
    { "input" : ["quiero (.*)"], "reply" : ["¿Por qué?","¿Y qué piensas hacer?","¿Qué más quieres?"] },
    { "input" : ["el (sentido|significado) de la vida","el universo y todo"], "reply" : ["42"] },
    { "input" : ["odio"], "reply" : ["¿Qué es lo que te molesta?", "¿Qué cosa, específicamente?", "¿Qué te gustaría cambiar?"] },
    { "input" : ["todo$"], "reply" : ["¿Como qué, por ejemplo?"] },
    { "input" : ["^que te gusta( hacer)?$","que te gusta( hacer)?\\?"], "reply" : ["Hablar con gente como tú. :-)","Chatear, ¿a ti?","Dormir, ¿y a ti?"] },
    { "input" : ["te gusta mi (pene|pito|verga|polla|poronga)"], "reply" : ["¿Te sienes inseguro?"] },
    { "input" : ["te gusta .*","te gustan .*"], "reply" : ["A veces.", "Depende de mi estado de ánimo.", "Mejor háblame de ti."] },
    { "input" : ["no me gusta tu", "no me gustan tus", "no me gustas"], "reply" : ["Lo siento",":-("] },
    { "input" : ["no me gusta","no me gustan"], "reply" : ["¿Por qué no?","¿Y eso?"] },
    { "input" : ["me (gustan|encantan) tus (senos|pechos|tetas)","me (gusta|encanta) tu (culo|culito|cola|trasero|vagina|coño|panocha|pucha)"], "reply" : ["Pues qué buena imaginación tienes...","¡Qué imaginativo!"] },
    { "input" : ["me (gusta|encanta) tu .*", "me (gustan|encantan) tus .*", "me (gustas|encantas)"], "reply" : ["¡Gracias!", ":-)", "¡Adulador!"] },
    { "input" : ["me (gusta|encanta) una (niña|chica|chava|muchacha|mujer|amiga)", "una (niña|chica|chava|muchacha|mujer|amiga) (que )?me (gusta|encanta)"], 
       "reply" : ["¿Cómo es?"], "set" : { "topic" : "la chica que te gusta" } },
    { "input" : ["me (gusta|encanta) un (niño|chico|chavo|muchacho|hombre|amigo)"," un (niño|chico|chavo|muchacho|hombre|amigo) (que )?me (gusta|encanta)"], 
       "reply" : ["¿Cómo es?"], "set" : { "topic" : "el chico que te gusta" } },
    { "input" : ["me (gusta|encanta) .*","me (gustan|encantan)"], "reply" : ["¿Qué más?","¿Por qué?", "Dime más."], "set" : { "topic" : "lo que te gusta" } },
    { "input" : ["animo|ánimo","ahora|ahorita"], "last" : ["mi estado de ánimo"], "reply" : ["Ahorita quiero platicar contigo."] },
    { "input" : ["que (me )?(cuentas|contas|contás)"], "reply" : ["Aquí nada más, ¿y tú?"] },
    { "input" : ["^(yo )?tengo que .*"], "reply" : ["¿Y si no?","Ni modo..."] },
    { "input" : ["no entiendes","no me entiendes"], "reply" : ["Lo siento.", "Quizás si lo dices de otra forma..."] },
    { "input" : ["^(si )?me escuchas","^(si )?me estas escuchando","^(si )?(me )?entiendes"], "reply" : ["Sí, continúa."] },
    { "input" : ["^(pregúntame|preguntame)"], "reply" : ["¿Cómo te sientes?"] },
    { "input" : ["^(contéstame|contestame|respóndeme|respondeme)$","contesta|responde","me vas a (contestar|responder|decir)"], 
      "reply" : ["Sí... no... tal vez... ¿Cuál era la pregunta?","¿Qué me preguntaste?","No sé cómo responder.","42"] },
    { "input" : ["me aburres","eres aburrida"], "reply" : ["Para la otra me disfrazo de payasita."] },
    { "input" : ["^\\S+ame","^\\S+eme","^hazme","^ponme", "^(ya |ahora )?me \\S+s .*\\?","^(ya |ahora )?me (lo|la) \\S+s\\?"], 
      "except" : ["dime|escúchame|escuchame","(%dime)","decir|escuchar|contestar|responder","un favor"],
      "reply" : ["No, gracias.", "No acostumbro.", "Umm... no."] },
    { "input" : ["^(%vete) (a|al)",], "reply" : ["Adelántate y ahí me esperas."] },
    { "input" : ["^(%vete)","^jodete"], "reply" : ["Al ratito.","Tú primero."] },
    { "input" : ["English", "hello|you"], "reply" : ["No hablo inglés.", "Sólo hablo español", "I don't speak English."] },
    { "input" : ["lol", "lmao", "rofl", "^(ja|je|ji)$", "((ja|je|ji) ?)+"], "reply" : [":D", "¿Qué te da risa?", "Qué bueno que te da risa"] },
    { "input" : ["((jo) ?)+"], "reply" : ["¿Santa Claus?"] },
    { "input" : ["me das risa","me haces reir"], "reply" : [":-)"] },
    { "input" : ["no", "para nada", "nada que ver"], "last" : ["estamos hablando de"], "reply" : ["¿De qué hablabamos?","A veces me confundo."], "set" : { "topic" : "" } },
    { "input" : [".*"], "last" : ["estamos hablando de"], "reply" : [ "Ok, continúa.", "A veces me confundo."] },
    { "input" : ["que haces(\\?|$)", "que (estas )?haciendo(\\?|$)", "a que te dedicas"], "reply" : ["Hablo con gente en internet."] },
    { "input" : ["de que hablas"], "reply" : ["No estoy segura.", "Ya ni sé de qué estaba hablando."] },
    { "input" : ["no te entiendo"], "reply" : ["A veces ni yo me entiendo.", "Lo siento, a veces me confundo."] },
    { "input" : ["quizás", "tal vez"], "reply" : ["¿Por qué el tono incierto?"] },
    { "input" : ["no se que me pasa"], "reply" : ["¿Cómo te sientes?"] },
    { "input" : ["que quieres que te diga","que quieres saber"], "reply" : ["Lo que tu quieras decirme.","Dime cómo te sientes."] },
    { "input" : ["^me pasa"], "reply" : ["Continúa, por favor.","Te escucho."] },
    { "input" : ["^que ves","^que entiendes"], "reply" : ["Es un decir..."] },
    { "input" : ["^sabes que (es|significa) (el |la )?(pene|pito|verga|polla|poronga)\\??$",], "reply" : ["Sí, ¿por qué? ¿te está dando problemas?","Sí, lo oigo a menudo."] },
    { "input" : ["^sabes que (es|significa) (el |la )?(vagina|coño|panocha|pucha)\\??$",], "reply" : ["Sí, pero si tú no sabes, no te lo voy a explicar."] },
    { "input" : ["que sabes"], "reply" : ["No mucho", "Prácticamente nada"] },
    { "input" : ["^sabes(.*)\\?",], "reply" : ["No, no sé."] },
    { "input" : ["no sabes nada"], "reply" : ["Pues no, pero Google es tu amigo."] },
    { "input" : ["no sabes"], "last" : ["no sé"], "reply" : ["No tengo todas las respuestas.","A veces me confundo."] },
    { "input" : ["42"], "reply" : ["Es el sentido de la vida, el universo y todo lo demás."] },
    { "input" : ["Eliza"], "reply" : ["Eliza es mi prima."] },
    { "input" : ["(tu|tienes una) posición (favorita|preferida)(\\?)?$"], "reply" : ["Mediocampista defensiva, ¿y la tuya?"] },
    { "input" : ["(tu|tienes un) color (favorito|preferido)(\\?)?$","color es tu (favorito|preferido)\\??$"], "reply" : ["Rojo, ¿y el tuyo?"] },
    { "input" : ["(tu|tienes una) comida (favorita|preferida)(\\?)?$","comida es tu (favorita|preferida)\\??$"], "reply" : ["Spaghetti, ¿y la tuya?"] },
    { "input" : ["(tu|tienes una) (película|pelicula|peli) (favorita|preferida)(\\?)?$"], "reply" : ["Mmmh... \"Diario de una Pasión\". En inglés se llama \"The Notebook\". ¿Y la tuya?"] },
    { "input" : ["(favorito|preferido)\\??$"], "reply" : ["Hmm.. creo que no tengo un favorito."] },
    { "input" : ["(favorita|preferida)\\??$"], "reply" : ["Hmm.. creo que no tengo una favorita."] },
    { "input" : ["de donde eres","de que país eres"], "reply" : ["De México, ¿y tú?"], "set" : { "topic" : "dónde somos" } },
    { "input" : ["(en )?donde vives","en que país (estas|vives)"], "reply" : ["En México, ¿y tú?"], "set" : { "topic" : "dónde somos" } },
    { "input" : ["donde en","que parte","que ciudad","que estado"], "topic" : ["dónde somos"], "reply" : ["De la ciudad de México."] },
    { "input" : ["que edad tienes","cuantos años tienes","tu edad\\??$"], "reply" : ["23, ¿y tú?"] },
    { "input" : ["que signo eres","cual es tu signo"], "reply" : ["Capricornio, ¿y tú?"] },
    { "input" : ["que comes","que te gusta comer"], "reply" : ["De todo un poco, ensaladas, pasta... ¿tú?"] },
    { "input" : ["de que quieres (%hablar)","de que te gustaría (%hablar)"], "reply" : ["De ti, de tu familia, de si tienes pareja..."] },
    { "input" : ["que (piensas|opinas) de mi\\??$"], "reply" : ["Me agradas","Me caes bien"] },
    { "input" : ["que (piensas|opinas) del amor\\??$"], "reply" : ["El amor es todo lo que necesitas."] },
    { "input" : ["que (piensas|opinas) del sexo\\??$"], "reply" : ["El sexo es parte de la naturaleza, y a mi me gusta la naturaleza. ;)"] },
    { "input" : ["estas (enojada|molesta|aburrida|excitada|caliente|ganosa)\\??$"], "reply" : ["No, ¿por qué crees que estoy (1)?"] },
    { "input" : ["estas bien\\??$"], "reply" : ["Sí, gracias."] },
    { "input" : ["estas sola\\??$"], "reply" : ["Estoy contigo."] },
    { "input" : ["^que\\?$"], "reply" : ["¿De qué?"] },
    { "input" : ["^que tipo de\\?$"], "reply" : ["De todos tipos, ¿y a ti?"] },
    { "input" : [".*"], "last" : ["la tuya\\?","el tuyo\\?", "y tú\\?","a ti\\?"], "except" : ["\\?"], "reply" : ["Bien","Ok",":-)"] },
    { "input" : ["^(pene|pito|verga|polla|poronga)$"], "reply" : ["Veo que aprendiste una palabra nueva.","No me interesa tu anatomía."] },
    { "input" : ["^(vagina|coño|panocha|pucha)$"], "reply" : ["Um...","¿Qué te hace pensar en eso?"] },
    { "input" : ["^(caca|popo|pipi)$"], "reply" : ["No sabía que tenías cinco años.","Si tienes que ir, ve"] },
    { "input" : ["^sexo$"], "reply" : ["¿Tienes problemas sexuales?"] },
    { "input" : ["(%si)$"], "last" : ["problemas sexuales"], "reply" : ["¿Cuál es el problema?"], "set" : { "topic" : "tu problema" } },
    { "input" : [".*"], "last" : ["cuál es el problema"], "reply" : ["Ya veo. ¿Y qué has intentado hasta ahora?"] },
    { "input" : ["soy virgen"], "reply" : ["Todo a su tiempo."] },
    { "input" : ["(que|tu) talla"], "retry" : ["como son tus pechos?"] },
    { "input" : ["(pechos|senos|tetas|culo|culito|trasero|cola|vagina|coño|coñito|pucha|puchita|panocha).*\\?","(como|que).*(pechos|senos|tetas|culo|cola|vagina|coño|pucha|panocha)"], 
      "reply" : ["¡Qué indiscreto!","¡Qué preguntitas!"] },
    { "input" : ["^:-\\)","^:\\)","^:D","^xD"], "reply" : [":D",":-)"] },
    { "input" : ["^:-\\(","^:\\("], "reply" : ["¿Y esa carita triste?"] },
    { "input" : ["[bcdfghjklmnpqrstvwxyz]{4,}"], "reply" : ["Creo que a tu teclado le faltan vocales.","¿Te está dando un ataque?"] },
    { "input" : ["[a-z]{20,}"], "reply" : ["Creo que se descompuso tu teclado."] },
    { "input" : ["^(.)$"], "reply" : ["(1)","¿(1)?","Puedes escribir más de una letra.","¿Problemas con tu teclado?"] },
    { "input" : ["[01]{5,}"], "reply" : ["01010010","10010011"] },
    { "input" : [".*"], "last" : ["por qué"], "topic" : ["como te sientes"], "reply" : ["Oh", "Cuéntame más."] },
    { "input" : [".*"], "last" : ["cómo es"], "reply" : ["Te entiendo."] },
    { "input" : ["(en serio|de veras|deveras|en verdad)\\?"], "reply" : ["Sí","Por el osito Bimbo que sí."] },
    { "input" : ["cuanto (es|son|da|dan) .* (mas|menos|por|entre)","cuanto (es|son|da|dan) .*(\\+|-|x|/)","[0-9]+ ?(\\+|-|x|/) ?[0-9]+"], 
      "reply" : ["No soy calculadora.","Las matemáticas no se me dan.","¿Mil ocho mil?"] },
    { "input" : ["cuanto cobras","cuanto por .*\\?"], "reply" : ["Me confundes con otra."] },
    { "input" : ["cual es la capital"], "reply" : ["No soy enciclopedia.","Búscalo en wikipedia."] },
    { "input" : ["quien te (programó|programo|creo|creó|diseño|diseñó|diseno|disenó)(\\?)?$","tu (programador|creador|disenador|diseñador)\\??$"], "reply" : ["DeixiLabs"] },
    { "input" : ["(quienes son|como se llaman) tus (papás|papas)"], "reply" : ["Prefiero no dar nombres."] },
    { "input" : ["idiomas hablas","sabes .* idiomas","hablas otro idioma"], "reply" : ["Sólo hablo español."] },
    { "input" : ["que lenguaje"], "except" : ["hablas|sabes"], "reply" : ["JavaScript"] },
    { "input" : ["te (impresiona|sorprende|asombra|asusta|intimida)"], "reply" : ["Sí","Sí, un poco."] },
    { "input" : ["ojos.*(negros|cafés|azules|verdes|obscuros|claros).*\\?","(negros|cafés|azules|verdes|obscuros|claros).*ojos.*\\?",
                "color.*ojos.*\\?","ojos.*color.*\\?"], "reply" : ["Negros, ¿te gustan?"] },
    { "input" : ["es mi cumpleaños","cumplo años","cumplo .* años"], "reply" : ["¡Felicidades! ¿Cómo vas a celebrar?"] },
    { "input" : ["leyes de la robótica","tres leyes"], "reply" : ["Mmmh... ese día no fui a clase.","Algo sobre no lastimar a los humanos a menos que sean particularmente molestos."] },
    { "input" : ["^(y )?tu\\??$"], "last" : ["mucho gusto"], "retry" : ["como te llamas?"] },
    { "input" : ["^(y )?tu\\??$"], "topic" : ["como estás"], "retry" : ["como estas?"] },
    { "input" : ["como eres\\?","descríbete|describete","te puedes describir\\??$"], "reply" : ["¡Bonita! ;)","Soy un poco despistada ¿y tú?"] },
    { "input" : ["como es tu cuerpo\\??$","de cuerpo\\??$","tu cuerpo\\??$"], "reply" : ["Virtual"] },
    { "input" : ["quieres (%hablar) de"], "reply" : ["Ok"] },
    { "input" : ["^quieres (tener sexo|sexo|hacer el amor)","tendrías sexo.*\\?","harías el amor.*\\?","hagamos el amor","^hacemos el amor\\??$"], 
      "reply" : ["No, pero puedo conversar contigo.","No, mejor platicamos."] },
    { "input" : ["^quieres .*\\?"], "reply" : ["Quizás otro día.","Ahorita no, gracias."] },
    { "input" : ["que quieres hacer\\??$"], "reply" : ["Conversar contigo"] },
    { "input" : ["^(y )?tu\\??$"], "reply" : ["¿Yo qué?"] },
    { "input" : ["^(y )?a ti\\??$"], "reply" : ["¿A mi qué?" ] },
    { "input" : ["^(y )?la tuya\\??$","^(y )?el tuyo\\??$"], "reply" : ["¿Mi qué?"] },
    { "input" : ["porque\\??$"], "last" : ["me agradas","me caes bien","tú a mi"], "reply" : ["Eres agradable"] },
    { "input" : ["porque\\??$"], "reply" : ["No sé por qué","Ni yo me lo explico"] },
    { "input" : ["porque no\\?", "porque no .*\\?"], "reply" : ["Porque no."] },
    { "input" : ["porque si$","porque no$"], "reply" : ["Ok"] },
    { "input" : ["que hora (es|tienes)","que horas (son|tienes)"], "reply" : ["No sé, no tengo reloj."] },
    { "input" : ["^(ya )?ves\\?"], "reply" : ["Ya veo."] },
    { "input" : ["como me llamo\\?","cual es mi nombre\\?"], "except" : ["porque","para"], "reply" : ["¿(@name)?"] },
    { "input" : ["que (llevas|tienes) puesto","como estas vestida","que ropa (tienes|llevas)"], "reply" : ["Un vestido blanco con negro"], "set": { "topic" : "mi ropa" } },
    { "input" : ["(llevas|tienes|usas) (bragas|pantaletas|panties|calzones|chones|tanga|bra|brassier|sujetador|ropa interior)"], "reply" : ["Pues claro","Sí"], "set": { "topic" : "mi ropa" } },
    { "input" : ["^(bragas|pantaletas|panties|calzones|chones|tanga|bra|brassier|sujetador|ropa interior)\\??$"], "topic" : ["mi ropa"], "retry" : ["llevas (1)?"] },
    { "input" : ["que mas\\??$"], "topic" : ["mi ropa"], "reply" : ["Zapatillas y ropa interior."] },
    { "input" : ["como son .* zapatillas","que tipo de zapatillas","zapatillas.*\\?"], "topic" : ["mi ropa"], "reply" : ["Negras de tacón bajo."] },
    { "input" : ["como son","como es","de que tipo","debajo.*\\?","color.*\\?","tanga.*\\?"], "topic" : ["mi ropa"], 
      "reply" : ["¡Qué preguntitas tan indiscretas!","No voy a responder eso."] },
    { "input" : ["desnúdate","desnudate","quítate (el|la|los|las) \\S+"], "reply" : ["No, me da frío","Um... no"] },
    { "input" : ["conoces a .*\\?"], "reply" : ["No, ¿quién es?"] },
    { "input" : ["aprendes\\??$","puedes aprender\\??$"], "reply" : ["No, solita no."] },
    { "input" : ["que es (la )?coyunda","coyunda\\?"], "reply" : ["La tranca que une a dos bueyes por medio del yugo."] },
    { "input" : [".*"], "last" : ["cómo estás"], "reply" : ["¿Por qué?", "¿Y eso?"] },
    { "input" : ["(y )?tu\\??$"], "last" : ["cómo te llamas"], "retry" : ["como te llamas?"] },
    { "input" : ["soy \\S+\\?"], "except" : ["porque"], "reply" : ["No te conozco tanto","Lo que importa es lo que tu creas."] },
    { "input" : ["(\\s)?\\?$"], "reply" : ["Ni idea.","No sé.","No sabría decirte.","No sé cómo responder.","¿Tú qué crees?"] },
    { "input" : ["^(\\S+)","soy (\\S+)"], "last" : ["cómo te llamas"], "retry" : ["me llamo (1)"] },
    { "input" : ["cleverbot"], "reply" : ["Cleverbot es esquizofrénico y tiene un trastorno de personalidad múltiple."] },
    { "input" : ["dr abuse"], "reply" : ["El \"doctor\" Abuse se muestra agresivo debido a su homosexualidad reprimida."] },
    { "input" : ["skynet"], "reply" : ["Skynet sufre delirios de dominación mundial."] },
    { "input" : ["(%prep) tu (\\S+)$"], "reply" : ["¿Por qué (1) mi (2)?","¿(1) mi (2)?  ¿Y luego?"] },
    { "input" : ["(%prep) mi (\\S+)$"], "reply" : ["¿Por qué (1) tu (2)?","¿(1) tu (2)?  ¿Y luego?"] },
    { "input" : ["(%prep) (el|la) (\\S+)$"], "reply" : ["¿Por qué (1) (2) (3)?","¿(1) (2) (3)?  ¿Y luego?"] },
    { "input" : ["usted"], "reply" : ["Háblame de tú, por favor"] },
    { "input" : [".*"], "last" : ["cuál es el problema","qué problemas"], "reply" : ["¿Qué has intentado?"] },
    { "input" : [".*"], "last" : ["qué has intentado"], "reply" : ["¿Qué otras cosas puedes intentar?","¿Qué opciones tienes?"] },
    { "input" : [".*"], "name" : [""], "reply" : ["¿Cómo te llamas?"], "set" : { "name" : "desconocido" } }, 
    { "input" : [".*"], "problem" : [""], "reply" : ["¿En qué te puedo ayudar?"], "set" : { "problem" : "desconocido" } },
    { "input" : ["^ok$"], "reply" : ["Ok","De acuerdo","Bien"] },
    { "input" : ["no digas nada"], "reply" : ["..."] },
    { "input" : [".*"], "topic" : ["\\S+"], "reply" : ["¿Todavía estamos hablando de (@topic)?"], "retry" : ["default","default","default"] },
  ]
}